version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - SERVER_PORT=8080
      - AI_ENDPOINT=https://auto-comment.gokulakrishnanr812-492.workers.dev/
      - AI_TIMEOUT=30
      - AI_DEFAULT_MODEL=default
      - LOG_LEVEL=debug 